EXE/UfolepBMX/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user

from .models import User
from .__init__ import db

auth = Blueprint("auth", __name__)

@auth.route("/login")
def login() :
    """Fonction liée au end-point "/login"

    Fonction affichant la page de connection

    Returns:
        Template: template login.html

    """
    return render_template("login.html")

@auth.route("/login", methods=["POST"])
def login_post() :
    """Fonction liée au end-point "/login" en methode POST

    Fonction gérant la connection

    Returns:
        Redirect: redirection vers views.home ou auth.login

    """
    username = request.form.get('username')
    password = request.form.get('password')
    remember_me = request.form.get('rememberMe')

    if username is not None and username != '' and password is not None and password != "" :
        if remember_me == 'on' :
            remember_me = True
        else :
            remember_me = False

        user = User.query.filter_by(username=username).first()
        if user is not None and check_password_hash(user.password, password) :
            login_user(user, remember=remember_me)

            return redirect(url_for('views.home'))

    return redirect(url_for('auth.login'))

@auth.route("/logout")
def logout() :
    """Fonction liée au end-point "/logout"

    Fonction déconnectant l'utilisateur

    Returns:
        Redirect: redirection vers views.home

    """
    logout_user()
    return redirect(url_for('views.home'))

EXE/UfolepBMX/website/views.py
from cmath import log
from hmac import new
from operator import index, indexOf
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from flask_login import login_required, current_user
import sqlalchemy
import datetime
import random
from math import ceil
import numpy as np
import os

import xlrd
import os
if os.name == "nt":
    os.environ['PATH'] = r"GTK3" + os.pathsep + os.environ['PATH']
import weasyprint
from flask_weasyprint import HTML, render_pdf

from .__init__ import db
from .models import User, Titulaire, Club, Sexe, Championnat, Championnat_type, Etape, Categorie_type, Participant_etape, Race_type, Couloir, Race, Participant_race, Manche, Participant_manche, Categorie, Participant_categorie

views = Blueprint("views", __name__)


def get_titulaires_dict(titulaires):
    """Fonction de création d'un dictionnaire de titulaires

    Certaines fonction nécessite une structure de données particulière, cette fonction la créée.

    Returns:
        Dict: dictionnaire de titulaires

    """

    to_return = []

    for titulaire in titulaires :

        club = Club.query.filter_by(id=titulaire.club_id).first()
        sexe = Sexe.query.filter_by(id=titulaire.sexe_id).first()

        to_return.append({
            "id": titulaire.id,
            "nom": titulaire.nom,
            "prenom": titulaire.prenom,
            "date_naissance": titulaire.date_naissance.strftime("%d/%m/%Y"),
            "club": club.ville[0].upper() + club.ville[1:],
            "sexe": sexe.denomination,
            "plaque": str(titulaire.numero_plaque),
        })

        # ancienne facon d'avoir la plaque :  "plaque": club.initiales.upper() + " " + str(titulaire.numero_plaque),

    return to_return

def check_titulaire_number(titulaires, number) :
    """Fonction de vérification de l'unicité de la plaque

    Fonction vérifiant si le numéro de plaque voulu n'existe pas déjà dans le club

    Returns:
        bool: vrai ou faux

    """

    for titulaire in titulaires :

        if titulaire.numero_plaque == number :

            return False
    return True


def get_championnats_dict() :
    """Fonction de création d'un dictionnaire de championnats

    Certaines fonction nécessite une structure de données particulière, cette fonction la créée.

    Returns:
        Dict: dictionnaire de championnats

    """

    championnats_list = Championnat.query.order_by(Championnat.annee.desc()).all()
    championnats = []

    for championnat in championnats_list :

        championnats.append({
            'id': championnat.id,
            'type': Championnat_type.query.filter_by(id=championnat.championnat_type_id).first().type,
            'annee': championnat.annee,
            'nb_etapes_max': str(Championnat_type.query.filter_by(id=championnat.championnat_type_id).first().nb_etapes_max),
            'nb_etapes_courant': str(len(championnat.etapes))
        })

    return championnats

def get_etapes_dict(championnat) :
    """Fonction de création d'un dictionnaire de étapes

    Certaines fonction nécessite une structure de données particulière, cette fonction la créée.

    Returns:
        Dict: dictionnaire de l'étapes

    """

    etapes_list = championnat.etapes
    etapes = []

    for etape in etapes_list :
        etapes.append({
            'id': etape.id,
            'club': Club.query.filter_by(id=etape.lieu_id).first().ville,
            'participants': len(Participant_etape.query.filter_by(etape_id=etape.id).all()),
            'nb_titulaires': len(Titulaire.query.all())
        })

    return etapes

def calcul_points_race(races) :
    """Fonction de calcul des points d'un race

    Fonction qui calcul les points en fonction de l'orde d'arrivé des pilotes à une manche

    Returns:
        non ne retourne rien mais modifie l'attribut resultat d'un participant à une race en faisant le cumul de ces points lors des différentes manches de la race 
        Dict: dictionnaire ordonné par ordre croissant des points reçus aux races d'une manche

    """
    resultats = {}
    for race in races :
        for manche in race.manches :
            for participation in manche.participations :
                if participation.titulaire_id in resultats :
                    resultats[participation.titulaire_id] += participation.resultat
                else :
                    resultats[participation.titulaire_id] = participation.resultat
        for participation in race.participations :
            participation.resultat = resultats[participation.titulaire_id]


@views.route("/")
@login_required
def home() :
    """Fonction liée au end-point "/"

    Fonction affichant la page d'acceuil.

    Returns:
        Template: template logged.html

    """

    return render_template("logged.html")

#Fonction affichant la liste des titulaires
@views.route("/titulaires/")
@login_required
def titulaires() :
    """Fonction liée au end-point "/titulaires/"

    Fonction affichant la liste des titulaires.

    Returns:
        Template: template titulaire.html

    """

    #Récupération des données nécessaires à l'affichage de la page
    titulaires = get_titulaires_dict(Titulaire.query.all())
    clubs = Club.query.all()
    sexes = Sexe.query.all()

    #Retour de la page populer des valeurs passées en argument
    return render_template("titulaires.html", title="tous", titulaires=titulaires, clubs=clubs, sexes=sexes)

@views.route('/titulaires/<club_id>/',methods=["POST","GET"])
@login_required
def titulaires_by_ville(club_id) :
    """Fonction liée au end-point "/titulaires/<club_id>/"

    Fonction affichant la liste des titulaires d'un club.

    Args:
        club_id : id du club

    Returns:
        Template: template titulaires.html

    """
    if request.method == "POST":
        #on est dans le cas où formulaire de création de titulaire nous a été soumis, on contrôle et on insère
        #le titulaire si controle ok
        add_titulaire(club_id=club_id)
        
    club = Club.query.filter_by(id=club_id).first()
    titulaires = get_titulaires_dict(Titulaire.query.filter_by(club_id = club.id).all())
    clubs = Club.query.all()
    sexes = Sexe.query.all()

    return render_template("titulaires.html", title=club.ville[0].upper() + club.ville[1:], titulaires=titulaires, clubs=clubs, sexes=sexes)

@views.route("/titulaires/", methods=['POST'])
@login_required
def add_titulaire(club_id=None) :
    """Fonction liée au end-point "/titulaires/ en method POST"
    Args:
        le nom de la template à utiliser pour le rendu (en fonction de là où le titulaire est créé)
    Fonction ajoutant un titulaire

    Returns:
        Redirect: redirection vers views.titulaire

    """
    template_to_return = ""
    clubs = Club.query.all()
    sexes = Sexe.query.all()
    new_titulaires = {}
    if club_id is None:
        new_titulaires = get_titulaires_dict(Titulaire.query.all())
        template_to_return = render_template("titulaires.html", title="tous", titulaires=new_titulaires, clubs=clubs, sexes=sexes, name=True)
    else:
        club = Club.query.filter_by(id=club_id).first()
        new_titulaires = get_titulaires_dict(Titulaire.query.filter_by(club_id=club_id).all())
        template_to_return = render_template("titulaires.html", title=club.ville[0].upper() + club.ville[1:], titulaires=new_titulaires, clubs=clubs, sexes=sexes)

    nom = request.form.get('name').upper() # On met le nom de famille en majuscule
    if nom is None or nom == "":
        return template_to_return
    # On met le prenom en minscule sauf la premiere lettre
    prenom = request.form.get('surname').lower()
    prenom = prenom[0].upper() + prenom[1:]
    if prenom is None or prenom == "" :
        return template_to_return
    date_naissance = request.form.get('birthDate')
    if date_naissance is None or date_naissance == "" or len(date_naissance.split("-")) != 3 or len(date_naissance.split("-")[2]) <= 0 or len(date_naissance.split("-")[2]) > 2 or len(date_naissance.split("-")[1]) <= 0 or len(date_naissance.split("-")[1]) > 2 or len(date_naissance.split("-")[0]) < 4:
        return template_to_return
    club_id_form = request.form.get('clubId')
    if club_id_form is None or club_id_form == "" or Club.query.filter_by(id=club_id_form).first() is None :
        return template_to_return    
    plaque = request.form.get('plaqueNb')
    #si la plaque contient la lettre on l'ajoute
    if plaque[0].isnumeric():
        numero = plaque
        plaque = (Club.query.filter_by(id=club_id_form).first()).initiales+numero
    #sinon
    else:
        plaque = plaque[0].upper() + plaque[1:]
        numero = plaque[1:] # on extrait le numero de la plaque
    # on verifie ensuite que la plaque n'existe pas déjà
    titulaires = Titulaire.query.all()
    PlaqueExist = 0
    for t in titulaires:
        if (t.numero_plaque == plaque) :
            PlaqueExist += 1

    if plaque is None or PlaqueExist >= 1 or plaque == "" or not check_titulaire_number( Club.query.filter_by(id=club_id_form).first().titulaires, plaque) is not None or int(numero)>=1000 or len(plaque)>4:
        return template_to_return
    sexe_id = request.form.get('sexeId')
    if sexe_id is None or sexe_id == "" or Sexe.query.filter_by(id=sexe_id).first() is None :
        return template_to_return
    date_naissance = datetime.datetime.strptime(date_naissance, '%Y-%m-%d')
    if len(plaque) == 2 :
        plaque = plaque[0] + "0" + plaque[1]
    new_titulaire = Titulaire(nom=nom.upper(), prenom=prenom, date_naissance=date_naissance, club_id=club_id_form, numero_plaque=plaque, sexe_id=sexe_id)
    db.session.add(new_titulaire)
    db.session.commit()

    return redirect(url_for('views.titulaires'))

@views.route("/add_titulaires/", methods=['GET','POST'])
@login_required
def add_titulaires() :
    """Fonction liée au end-point "/titulaires/"

    Fonction ajoutant des titulaires via un fichier xls

    Returns:
        Redirect: redirection vers views.titulaire

EXE/UfolepBMX/website/templates/championnats.html
{% extends "logged.html" %}

{% block logged_css %}
<link
    href="{{ url_for('static', filename='clubs.css') }}"
    rel="stylesheet"
>
{% endblock %}

{% block left_col %}
<form class="" method="post">
    <div class="title horizontal-flex mb-4">
        <h3>Ajouter un championnat</h3>
    </div>
    <div class="mb-4">
        <label for="type" class="form-label">Type</label>
        <select id="type" name="championnatTypeId" class="form-select {% if type %}is-invalid{% endif %}">
            <option value="none" selected>Choisir un type</option>
            {% for championnat_type in championnat_types %}
            <option value="{{ championnat_type.id }}">{{ championnat_type.type }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-floating mb-4">
        <input type="number" class="form-control {% if annee %}is-invalid{% endif %}" id="annee" name="annee">
        <label for="annee" class="form-label">Année</label>
    </div>
    <div class="horizontal-flex">
        <button type="submit" class="btn btn-outline-primary">Ajouter</button>
    </div>
</form>
{% endblock %}

{% block right_col %}
<div class="title mb-4">
    <h2>Championnats</h2>
</div>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Type</th>
            <th scope="col">Année</th>
            <th scope="col">Etape(s)</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for championnat in championnats %}
        <tr>
            <th scope="row" onclick="window.location='{{ url_for('views.etapes', championnat_id=championnat['id'])}}';">{{ loop.index }}</th>
            <td onclick="window.location='{{ url_for('views.etapes', championnat_id=championnat['id'])}}';">{{ championnat['type'] }}</td>
            <td onclick="window.location='{{ url_for('views.etapes', championnat_id=championnat['id'])}}';">{{ championnat['annee'] }}</td>
            <td onclick="window.location='{{ url_for('views.etapes', championnat_id=championnat['id'])}}';">{{ championnat['nb_etapes_courant'] + "/" + championnat['nb_etapes_max'] }}</td>
            <td class="img"><a href="" onclick="delete_championnat(event, {{ championnat['id'] }}, '{{ championnat['annee'] }}', '{{ championnat['type'] }}' )"><img src="{{ url_for('static', filename='delete.svg') }}" alt="Supprimer"></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}


{% block logged_js %}
<script type="text/javascript">
    $('#championnats').addClass('active');

        
    function delete_championnat(event, championnat_id, championnat_annee, championnat_type) {
        let nomChampionnat =championnat_type + " " + championnat_annee
        if (clicked(event, nomChampionnat)) {
            $.ajax(
                {
                    url: "{{ url_for('views.delete_championnat') }}",
                    type: "POST",
                    data: {
                        "championnat_id": championnat_id,
                    },
                    success: function(result){
                        location.reload();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        if(xhr.status == 500) {
                            alert("Erreur de suppression (serveur)");
                        }
                        location.reload();
                    }
                }
            );
        }
    }


</script>
{% endblock %}

EXE/UfolepBMX/website/templates/classement_etape_categories_pdf.html
<!DOCTYPE html>
<html>
    <head>
        <title>rendu pdf classement étape</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='classement_etape_pdf.css') }}">
    </head>
    <body>
        <h1>Classement d'étape championnat  : {{ etape.championnat.championnat_type.type }} - {{ etape.championnat.annee }} - etape : {{ etape.club.ville }}</h1>
        {% for classement_transforme in liste_classements %}
        <h2>{{ liste_categories[loop.index - 1].categorie_type.name }}</h2>
        <table style="width:95%">
            <thead>
                <th scope="col">nom - prenom</th>
                <th scope="col">club</th>
                <th scope="col">plaque</th>
                <th scope="col">nombre de points</th>
                <th scope="col">classement</th>
            </thead>
            <tbody>
                {% for position in classement_transforme %}
                <tr>
                    <td>{{ position[0].nom }} {{ position[0].prenom }}</td>
                    <td>{{ position[0].club.ville }} </td>
                    <td>{{ position[0].numero_plaque }}</td>
                    <td>{{ position[1] }}</td>
                    <td>{{ loop.index }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endfor %}
    </body>
</html>

EXE/UfolepBMX/website/templates/classement_etape_pdf.html
<!DOCTYPE html>
<html>
    <head>
        <title>rendu pdf classement étape</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='classement_etape_pdf.css') }}">
    </head>
    <body>
        <h1>Classement d'étape championnat  : {{ etape.championnat.championnat_type.type }} - {{ etape.championnat.annee }} -  {{ categorie_type.name }} - etape : {{ etape.club.ville }}</h1>
        <table style="width:95%">
            <thead>
                <th scope="col">nom - prenom</th>
                <th scope="col">club</th>
                <th scope="col">plaque</th>
                <th scope="col">nombre de points</th>
                <th scope="col">classement</th>
            </thead>
            <tbody>
                {% for position in classement_transforme %}
                <tr>
                    <td>{{ position[0].nom }} {{ position[0].prenom }}</td>
                    <td>{{ position[0].club.ville }} </td>
                    <td> {{ position[0].numero_plaque }}</td>
                    <td>{{ position[1] }}</td>
                    <td>{{ loop.index }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>
</html>

EXE/UfolepBMX/website/templates/classement_general_pdf.html
<!DOCTYPE html>
<html>
    <head>
        <title>Classement général</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='classement_etape_pdf.css')}}">
    </head>
    <body>
        <h1>Classement général : {{ championnat.championnat_type.type }} {{ championnat.annee }}</h1>
        <table style="width:95%">
            <thead>
                <tr>
                    <th>plaque</th>
                    <th>nom - prenom</th>
                    <th>club</th>
                    <!-- boucle sur les différentes étapes pour afficher les initiales de club-->
                    {% for etape in liste_etapes %}
                        <th colspan="2">{{ etape.club.initiales }}</th>
                    {% endfor %}
                    <th colspan="2">Total Pts et classement</th>
                </tr>
            </thead>
            <tbody>
                <!-- boucle sur les différentes entrées des classement d'étapes et sur celles du classement général -->
                {% for categorie in classement_general_global %}
                    {% if categorie is not string %}
                        <tr>
                            <th class="categorie_name" scope="col" colspan="{{ 5 + liste_etapes|length *2 }}">
                                {{ categorie.name }}
                            </th>
                        </tr>
                    {% endif %}    
                    {% for pilote in classement_general_global[categorie]['general'] %}                                <tr>
                                    <td>
                                        {{ pilote.numero_plaque }}
                                    </td>
                                    <td>
                                        {{ pilote.nom }} - {{ pilote.prenom }}
                                    </td>
                                    <td>
                                        {{ pilote.club.ville }}
                                    </td>
                                    {% for entree_classement_etape in classement_general_global[categorie] %}
                                        {% if entree_classement_etape is not string %}
                                            {% for pilote_etape in classement_general_global[categorie][entree_classement_etape] %}
                                            {% if pilote_etape[0] == pilote %}
                                                <td>
                                                    {{ pilote_etape[1] }}
                                                </td>
                                                <td>
                                                    {{ loop.index }}
                                                </td>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                    {% for i in range(championnat.etapes|length - nb_etapes_finies) %}
                                    <td></td>
                                    <td></td>
                                    {% endfor %}
                                    <td>{{ classement_general_global[categorie]['general'][pilote] }}</td>
                                    <td>{{ loop.index }}</td>
                                </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </body>
</html>

EXE/UfolepBMX/website/templates/clubs.html
{% extends "logged.html" %}

{% block logged_css %}
<link
    href="{{ url_for('static', filename='clubs.css') }}"
    rel="stylesheet"
>
{% endblock %}


{% block edit_form %}
<div id="edit_form">
    <div id="container-form">
        <div class="title horizontal-flex mg">
            <h3>Modifier le club</h3>
        </div>

        <div class="mg">
            <label for="club_name" class="form-label">Nom</label>
            <input type="text" id="club_name" name="club_name" class="form-control {% if club_name %}is-invalid{% endif %}">
        </div>

        <div class="mg">
            <label for="club_init" class="form-label">Initiale(s)</label>
            <input type="text" id="club_init" name="club_init" class="form-control {% if club_init %}is-invalid{% endif %}">
        </div>

        <div id="container-btns">
            <button class="btn btn-outline-danger" id="btn-cancel" onclick="hideEditForm(event)"> Annuler </button>
            <button type="submit" class="btn btn-outline-primary" onclick="editClub()" id="btn-ok"> Confirmer </button>
        </div>

    </div>

</div>
{% endblock %}

{% block left_col %}
<form class="" method="post">
    <div class="title horizontal-flex mb-4">
        <h3>Ajouter un club</h3>
    </div>
    <div class="form-floating mb-4">
        <input type="text" class="form-control {% if ville %}is-invalid{% endif %}" id="city" name="city">
        <label for="city" class="form-label">Nom Club</label>
    </div>
    <div class="form-floating mb-4">
        <input type="text" class="form-control {% if initiales %}is-invalid{% endif %}" id="initiales" name="initiales" aria-describedby="initialesHelp">
        <label for="initiales" class="form-label">Initiale(s)</label>
        <div id="initialesHelp" class="form-text">Initiale(s) présent sur les plaques des pilotes</div>
    </div>
    <div class="horizontal-flex">
        <button type="submit" class="btn btn-outline-primary">Ajouter</button>
    </div>
</form>
{% endblock %}

{% block right_col %}
<div class="title mb-4">
    <h2>Clubs</h2>
</div>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nom club</th>
            <th scope="col">Initiale(s)</th>
            <th scope="col">Nombres de titulaires</th>

            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for club in clubs %}
        <tr>
            <th scope="row">{{ loop.index }}</th>
            <td onclick="window.location='{{ url_for('views.titulaires_by_ville', club_id=club.id)}}';">{{ club.ville[0]|upper + club.ville[1:] }}</td>
            <td onclick="window.location='{{ url_for('views.titulaires_by_ville', club_id=club.id)}}';"> {{ club.initiales }}</td>
            <td onclick="window.location='{{ url_for('views.titulaires_by_ville', club_id=club.id)}}';" >{{ club.titulaires|length }}</td>
            <td class="img"><img src="{{ url_for('static', filename='edit.png') }}" onclick="showEditForm(event, {{club.id}}, '{{ (club.ville[0]|upper + club.ville[1:]) }}', '{{ club.initiales }}')"  alt="Modifier"></td>
            <td class="img"><img src="{{ url_for('static', filename='delete.svg') }}" onclick="deleteClub(event, {{club.id}}, '{{ club.ville[0]|upper + club.ville[1:] }}')" alt="Supprimer"></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}



{% block logged_js %}
<script type="text/javascript">
    $('#clubs').addClass('active');

    var CLUB_ID = -1

    function showEditForm(e, club_id, club_name, club_init) {

        e.preventDefault();  // cette methode empeche le rechargement de la page
        CLUB_ID = club_id

        document.getElementById('club_name').value = club_name;
        document.getElementById('club_init').value = club_init;
        // on fait apparaitre le formulaire d'edition
        document.getElementById('edit_form').style.display = "flex";

    }


    function hideEditForm(e) {
        e.preventDefault();
        document.getElementById('edit_form').style.display = "none";
    }


    function editClub() {
        club_name = document.getElementById('club_name').value;
        club_init = document.getElementById('club_init').value;
        $.ajax(
        {
            url: "/clubs/"+CLUB_ID,
            type: "POST",
            data: {
                "club_name": club_name,
                "club_init": club_init
            },
            success: function(result){
                location.reload();
            }
        })
    }

    function deleteClub(e, club_id, club_ville) {
        e.preventDefault();
        if (clicked(event, club_ville)) {
            $.ajax(
                {
                    url: "{{ url_for('views.delete_club') }}",
                    type: "POST",
                    data: {
                        "club_id": club_id,
                    },
                    success: function(result){
                        alert(result.message)
                        location.reload();
                    }
                }
            );
        }
    }

</script>
{% endblock %}

EXE/UfolepBMX/website/templates/etapes.html
{% extends "logged.html" %}

{% block logged_css %}
<link
    href="{{ url_for('static', filename='clubs.css') }}"
    rel="stylesheet"
>
{% endblock %}

{% block left_col %}
<form class="" method="post">
    <div class="title horizontal-flex mb-4">
        <h3>Ajouter une etape</h3>
    </div>
    <div class="mb-4">
        <label for="lieu" class="form-label">Club Organisateur</label>
        <select id="lieu" name="lieuId" class="form-select {% if lieu %}is-invalid{% endif %}">
            <option value="none" selected>Choisir un lieu</option>
            {% for club in clubs %}
            <option value="{{ club.id }}">{{ club.ville[0]|upper + club.ville[1:] }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="horizontal-flex">
        <input type="hidden" name="championnatId" value="{{ championnat.id }}">
        <button style="margin-bottom: 12px;" type="submit" class="btn btn-outline-primary">Ajouter</button>
    </div>
</form>
<form method="post" action="{{url_for('views.generer_pdf_classement_general',championnat_id=championnat.id)}}">
    <div class="horizontal-flex">    
        <button type="submit" class="btn btn-outline-primary">Classement general</button>
    </div>
</form>
{% endblock %}

{% block right_col %}
<div class="title mb-4">
    <div class="center-flex me-2">
        <a href="{{ url_for('views.championnats') }}"><img class="back" src="{{ url_for('static', filename='back.svg') }}" alt="Retour"></a>
    </div>
    <h2>Etapes : {{ championnat_type }} - {{ championnat.annee }}</h2>
</div>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Club Organisateur</th>
            <th scope="col">Participants</th>
            <th> <!-- pour l'image --> </th>
        </tr>
    </thead>
    <tbody>
        {% for etape in etapes %}
        <tr>
            <th scope="row" onclick="window.location='{{ url_for('views.etape', championnat_id=championnat.id, etape_id=etape['id'])}}';">{{ loop.index }}</th>
            <td onclick="window.location='{{ url_for('views.etape', championnat_id=championnat.id, etape_id=etape['id'])}}';">{{ etape['club'] }}</td>
            <td onclick="window.location='{{ url_for('views.etape', championnat_id=championnat.id, etape_id=etape['id'])}}';">{{ etape['participants'] }}/{{ etape['nb_titulaires'] }}</td>
            <td class="img"><a href="#" onclick="delete_etape({{ etape['id'] }}, event)"><img src="{{ url_for('static', filename='delete.svg') }}" alt="Supprimer"></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}


{% block logged_js %}
<script type="text/javascript">
    $('#etapes').addClass('active');
    function delete_etape(etape_id, event) {
        if (clicked(event)) {
            $.ajax(
                {
                    url: "{{ url_for('views.delete_etape') }}",
                    type: "POST",
                    data: {
                        "etape_id": etape_id,
                    },
                    success: function(result){
                        location.reload();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        if(xhr.status == 500) {
                            alert("Erreur de suppression");
                        }
                        location.reload();
                    }
                }
            );
        }
    }

</script>
{% endblock %}

EXE/UfolepBMX/website/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('views.home') }}">
            <img class="logo" src="{{ url_for('static', filename='Logo.svg') }}" alt="UFOLEP">
        </a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a id="clubs" class="nav-link" href="{{ url_for('views.clubs') }}">Clubs</a>
                </li>
                <li class="nav-item">
                    <a id="titulaires" class="nav-link" href="{{ url_for('views.titulaires') }}">Titulaires</a>
                </li>
                <li class="nav-item">
                    <a id="championnats" class="nav-link" href="{{ url_for('views.championnats') }}">Championnats</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="btn btn-outline-danger" href="{{ url_for('auth.logout') }}">Déconnexion</a>
                </li>
            </ul>
        </div>
    </div>
</nav>